---
test:
  image: continuumio/miniconda3:4.8.2
  script:
    - conda env create -f environment.yml
    - source activate makefile2dot
    - make check
  only:
    - merge_requests

deliver:
  image: continuumio/miniconda3:4.8.2
  script:
    - conda env create -f environment.yml
    - source activate makefile2dot
    - conda config --set anaconda_upload no
    - conda build . --croot /tmp
    - export FILEPATH=/tmp/linux-64/makefile2dot-$CI_COMMIT_TAG-py37_0.tar.bz2
    - anaconda -t $ANACONDA_AUTH upload -u chadsgilbert $FILEPATH --force
  only:
    - tags
  except:
    - branches
