---
test:
  image: continuumio/miniconda3:4.8.2
  script:
    - conda env create -f environment.yml
    - source activate makefile2dot
    - make check
  only:
    - merge_requests

deliver:
  image: continuumio/miniconda3:4.8.2
  script:
    - conda env create -f environment.yml
    - source activate makefile2dot
    - conda config --set anaconda_upload yes
    - anaconda login -u $(CONDA_USER) -p $(CONDA_PASS)
    - conda build .
  only:
    - master
