---
test:
  image: continuumio/miniconda3:4.8.2
  script:
    - conda env create -f environment.yml
    - conda activate makefile2dot
    - pycodestyle makefile2dot/
    - pytest
  only:
    - merge_requests

deliver:
  image: continuumio/miniconda3:4.8.2
  script:
    - conda env create -f environment.yml
    - conda activate makefile2dot
    - conda config --set anaconda_upload yes
    - conda build .
    - anaconda login -u $(CONDA_USER) -p $(CONDA_PASS)
  only:
    - master
