package:
  name: makefile2dot
  version: {{CI_COMMIT_TAG}}

source:
  path: .

build:
  script: python setup.py install -f

requirements:
  host:
    - python
    - pip
    - graphviz
    - python-graphviz
  run:
    - python
    - graphviz
    - python-graphviz
